[project]
name = "gb-basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "corner>=2.3.0",
    "eryn>=1.2.6",
    "h5py>=3.16.0",
    "healpy>=1.20.0",
    "jax>=0.11.2",
    "jaxgb>=0.2.2",
    "lisaconstants>=2.0.2",
    "lisaorbits>=3.1.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pytdi>=2.2.1",
    "segwo>=2.0.0",
]
